<?php

return [

    'hero' => [
        'eyebrow' => 'Est. 2001 · South Africa → Middle East → USA',
        'title' => 'The Verrips',
        'title_accent' => 'Family',
        'subtitle' => 'Roy · Angela · Nathan · Luke · Jordan · Don',
    ],

    'photos' => [
        [
            'src' => 'resources/images/verrips-2025.png',
            'alt' => 'Roy, Luke, Don, Nathan and Angela — Reidville, SC 2025',
            'people' => 'Roy, Luke, Don, Nathan and Angela',
            'location' => 'Reidville, SC',
            'year' => '2025',
            'span' => 'big',
            'focus' => 'center',
        ],
        [
            'src' => 'resources/images/verrips-2023.png',
            'alt' => 'Don and Jenny Kirkwood, Luke, Angela, Roy, Nathan and Henri — Reidville, SC 2023',
            'people' => 'Don & Jenny Kirkwood, Luke, Angela, Roy, Nathan, Henri',
            'location' => 'Reidville, SC',
            'year' => '2023',
            'span' => 'big',
            'focus' => 'center',
        ],
        [
            'src' => 'resources/images/verrips-2022.png',
            'alt' => 'Nathan, Don and Jenny Kirkwood, Angela, Roy and Luke — Greer, SC 2022',
            'people' => 'Nathan, Don & Jenny Kirkwood, Angela, Roy, Luke',
            'location' => 'Greer, SC',
            'year' => '2022',
            'span' => 'wide',
            'focus' => 'center 30%',
        ],
        [
            'src' => 'resources/images/verrips-2021.png',
            'alt' => 'Nathan, Angela, Roy and Luke — Naperville, IL 2021',
            'people' => 'Nathan, Angela, Roy and Luke',
            'location' => 'Naperville, IL',
            'year' => '2021',
            'span' => 'wide',
            'focus' => 'center 25%',
        ],
        [
            'src' => 'resources/images/verrips-2020.png',
            'alt' => 'Luke, Roy, Nathan and Angela — Naperville, IL 2020',
            'people' => 'Luke, Roy, Nathan and Angela',
            'location' => 'Naperville, IL',
            'year' => '2020',
            'span' => 'wide',
            'focus' => 'center 10%',
        ],
        [
            'src' => 'resources/images/verrips-2018b.png',
            'alt' => 'Luke, Angela, Roy and Nathan — Naperville, IL 2018',
            'people' => 'Luke, Angela, Roy and Nathan',
            'location' => 'Naperville, IL',
            'year' => '2018',
            'span' => '',
            'focus' => 'center',
        ],
        [
            'src' => 'resources/images/verrips-2014.png',
            'alt' => 'Nathan, Angela, Luke and Roy — Doha, Qatar 2014',
            'people' => 'Nathan, Angela, Luke and Roy',
            'location' => 'Doha, Qatar',
            'year' => '2014',
            'span' => '',
            'focus' => 'center',
        ],
        [
            'src' => 'resources/images/verrips-2012.png',
            'alt' => 'Nathan, Roy, Angela and Luke — Abu Dhabi 2012',
            'people' => 'Nathan, Roy, Angela and Luke',
            'location' => 'Abu Dhabi, UAE',
            'year' => '2012',
            'span' => 'xwide',
            'focus' => 'center 25%',
        ],
        [
            'src' => 'resources/images/verrips-2010.png',
            'alt' => 'Nathan, Angela, Luke and Roy — Dubai 2010',
            'people' => 'Nathan, Angela, Luke and Roy',
            'location' => 'Dubai, UAE',
            'year' => '2010',
            'span' => '',
            'focus' => 'center',
        ],
        [
            'src' => 'resources/images/verrips-2009.png',
            'alt' => 'Roy, Angela, Nathan and Luke — Dubai, UAE 2009',
            'people' => 'Roy, Angela, Nathan and Luke',
            'location' => 'Dubai, UAE',
            'year' => '2009',
            'span' => 'big',
            'focus' => 'center',
        ],
        [
            'src' => 'resources/images/verrips-2008.png',
            'alt' => 'Angela, Luke, Nathan and Roy — Dubai, UAE 2008',
            'people' => 'Angela, Luke, Nathan and Roy',
            'location' => 'Dubai, UAE',
            'year' => '2008',
            'span' => 'big',
            'focus' => 'center',
        ],
        [
            'src' => 'resources/images/verrips-2006.png',
            'alt' => 'Angela, Luke, Nathan and Roy — Dubai, UAE 2006',
            'people' => 'Angela, Luke, Nathan and Roy',
            'location' => 'Dubai, UAE',
            'year' => '2006',
            'span' => 'xbig',
            'focus' => 'center',
        ],
        [
            'src' => 'resources/images/verrips-2004.png',
            'alt' => 'Rachel, Angela, Roy and Nathan — Dubai, UAE 2004',
            'people' => 'Rachel, Angela, Roy and Nathan',
            'location' => 'Dubai, UAE',
            'year' => '2004',
            'span' => 'xbig',
            'focus' => 'center',
        ],
    ],

    'gallery' => [
        'caption' => 'Years of memories, from Dubai to South Carolina',
    ],

    'about' => [
        'heading' => 'About Us',
        'tagline' => 'A Christian Family',
        'paragraphs' => [
            'We are <strong>Roy, Angela, Nathan</strong> and <strong>Luke Verrips</strong>, a
            <a href="#believe" class="underline" style="color: #4a6741;">Christian</a> family living in
            Reidville, South Carolina since the summer of 2022 when Angela\'s parents,
            <strong>Don</strong> and <strong>Jenny (Kirkwood)</strong>, came to live with us.  <strong>Jordan</strong> joined our family in 2025.',
            'We are originally from South Africa, and spent about 15 years living in the Middle East (Dubai,
            Abu Dhabi, and Doha, Qatar) before immigrating to the US in 2016. intially living in the Chicagoland area.',
            'We pray and trust that God will continue to strengthen us in His mercy and grace, and that
            we may be a blessing to those He brings across our path.',
        ],
        'quote' => [
            'text' => 'Our Saviour is Gentle and Lowly in heart.',
            'citation' => 'Matthew 11:29',
            'citation_url' => 'https://esv.org/Matthew11:29b',
        ],
    ],

    'family_section' => [
        'heading' => 'Our Family',
    ],

    'members' => [
        [
            'id' => 'roy',
            'name' => 'Roy',
            'photo' => 'resources/images/Roy-2021-Smile-300x300.png',
            'focus' => 'center',
            'role' => 'IT Director',
            'bio' => 'Works at Auro Hotels in Greenville, SC. When not working, Roy loves reading and dabbles in PHP, JavaScript and Laravel on the side.',
            'church' => ['name' => 'Reidville PCA', 'url' => 'https://reidvillepca.org'],
            'links' => [
                ['label' => 'LinkedIn',  'url' => 'https://www.linkedin.com/in/rverrips'],
                ['label' => 'Instagram', 'url' => 'https://www.instagram.com/rverrips'],
                ['label' => 'Facebook',  'url' => 'https://www.facebook.com/rverrips'],
                ['label' => 'Keybase',   'url' => 'https://keybase.io/rverrips'],
            ],
        ],
        [
            'id' => 'angela',
            'name' => 'Angela',
            'photo' => 'resources/images/angela-300x300.png',
            'focus' => 'top',
            'role' => 'Bookkeeper / QuickBooks Pro Advisor',
            'bio' => 'Works from home as a bookkeeper and QuickBooks Pro Advisor. Also a Norwex consultant and keeps our home a safe haven. Her oven-baked mac &amp; cheese is legendary — come hungry!',
            'church' => ['name' => 'Reidville PCA', 'url' => 'https://reidvillepca.org'],
            'links' => [
                ['label' => 'LinkedIn', 'url' => 'https://www.linkedin.com/in/angela-verrips'],
                ['label' => 'Norwex',   'url' => 'https://angelaverrips.norwex.biz'],
                ['label' => 'Facebook', 'url' => 'https://www.facebook.com/averrips/'],
            ],
        ],
        [
            'id' => 'nathan',
            'name' => 'Nathan',
            'photo' => 'resources/images/nathan-300x300.png',
            'focus' => 'top',
            'role' => 'Ophthalmic Scribe',
            'bio' => 'Works at Palmetto Eye and Laser Center, Boiling Springs, SC.  Loves the Gray Havens, Lord of the Rings lore, and board games. Part-time student at USC Upstate.',
            'church' => ['name' => 'Heritage Bible Church', 'url' => 'https://heritagegvl.com'],
            'links' => [
                ['label' => 'LinkedIn', 'url' => 'https://www.linkedin.com/in/nverrips/'],
            ],
        ],
        [
            'id' => 'luke',
            'name' => 'Luke',
            'photo' => 'resources/images/luke-300x300.png',
            'focus' => 'top',
            'role' => 'Swing Dancer',
            'bio' => 'Loves deep conversation, Covenant Theology, Brandon Sanderson and Swing Dancing. Posts songs to Instagram as <em>Skilsings</em>. Works at Chick-fil-A, Duncan.',
            'church' => ['name' => 'Woodruff Road PCA', 'url' => 'https://www.woodruffroad.com'],
            'links' => [
                ['label' => 'Instagram (SkilfulArcher)', 'url' => 'https://www.instagram.com/skilfularcher'],
                ['label' => 'Instagram (Skilsings)',      'url' => 'https://www.instagram.com/skilsings'],
                ['label' => 'YouTube',                    'url' => 'https://www.youtube.com/@skilfularcher'],
            ],
        ],
        [
            'id' => 'jordan',
            'name' => 'Jordan',
            'photo' => 'resources/images/jordan-600x600.png',
            'focus' => 'top',
            'role' => 'Daughter-in-Love',
            'bio' => 'Jordan has been living with us since late 2025. She is a talented artist and loves to cook so has been a great addition to our family.',
            'church' => ['name' => 'Woodruff Road PCA', 'url' => 'https://www.woodruffroad.com'],
        ],
        [
            'id' => 'don',
            'name' => 'Don',
            'photo' => 'resources/images/don-300x300.png',
            'focus' => 'object-top',
            'role' => 'Wuvie',
            'bio' => 'Angela\'s Dad, known as "Wuvie" by the grandkids, has been living with us since 2022, after immigrating from South Africa. Records weekly sermon to YouTube.',
            'church' => ['name' => 'Roebuck PCA', 'url' => 'https://roebuckpca.com'],
            'links' => [
                ['label' => 'YouTube',        'url' => 'https://www.youtube.com/@donaldkirkwood'],
                ['label' => 'DonKirkwood.com', 'url' => 'https://www.donkirkwood.com'],
            ],
        ],
        [
            'id' => 'rachel',
            'name' => 'Rachel',
            'photo' => 'resources/images/rachel-300x300.png',
            'focus' => 'object-center',
            'role' => 'In God\'s Presence',
            'bio' => 'Received from God on March 2004. Her constant smile touched everyone it fell upon and we are honoured that God shared her with us, even for such a short time. Returned to God November 2004.',
            'links' => [],
            'memorial' => true,
            'memorial_year' => '2004',
        ],
        [
            'id' => 'jenny',
            'name' => 'Jenny',
            'photo' => 'resources/images/jenny-300x300.png',
            'focus' => 'object-top',
            'role' => 'In God\'s Presence',
            'bio' => 'Angela\'s Mom. Jenny immigrated with Don from South Africa in 2022 to live with us in Reidville, SC. She went on ahead to be with our Lord in November 2024.',
            'links' => [],
            'memorial' => true,
            'memorial_year' => '2024',
        ],
    ],

    'believe' => [
        'heading' => 'What We Believe',
        'tagline' => 'Protestant · Evangelical · Reformed',
        'description' => 'We are a Christian family who believe the Bible to be God\'s true word. This 7-minute video
            offers a brief summary of what it means to be a Christian.',
        'video_id' => 'kbcvuu8lCFg',
        'contact_text' => 'Questions? <a href="mailto:roy@verrips.org" class="underline" style="color: #6a7c59;">Email us</a> — we\'d love to talk.',
    ],

];
